language: 'node_js'
node_js: '8'

before_script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  local_dir: dist
  keep_history: true
  on:
    branch: master